#nullable enable
using System;

namespace ElffyGenerator
{
    internal static class GeneratorUtil
    {
        public static string GetGeneratorSigniture(Type generatorType)
        {
            return 
@$"/* 
   Auto generated by a source generator.
   Generator: {generatorType.FullName} (Assembly: {generatorType.Assembly.FullName})
*/

";
        }
    }
}
